function C = coriolisMatrix(q, dq, p)

    % q is in radians
    % dq is in rad/s

    theta2 = q(2);
    theta3 = q(3);

    dtheta1 = dq(1);
    dtheta2 = dq(2);
    dtheta3 = dq(3);

    H2 = ...
        2*(p.Ixx2 - p.Iyy2 - p.m2*p.lc2^2) ...
        *sin(theta2)*cos(theta2) ...
        + 2*(p.Ixx3 - p.Iyy3) ...
        *sin(theta2 + theta3)*cos(theta2 + theta3) ...
        - 2*p.m3 ...
        *(p.l2*cos(theta2) + p.lc3*cos(theta2 + theta3)) ...
        *(p.l2*sin(theta2) + p.lc3*sin(theta2 + theta3));

    H3 = ...
        2*(p.Ixx3 - p.Iyy3) ...
        *sin(theta2 + theta3)*cos(theta2 + theta3) ...
        - 2*p.m3*p.lc3 ...
        *(p.l2*cos(theta2) + p.lc3*cos(theta2 + theta3)) ...
        *sin(theta2 + theta3);

    P3 = ...
        -2*p.m3*p.l2*p.lc3*sin(theta3);

    Q3 = ...
        -p.m3*p.l2*p.lc3*sin(theta3);

    C = [
        H2*dtheta2 + H3*dtheta3, ...
        0, ...
        0;

        -0.5*H2*dtheta1, ...
        P3*dtheta3, ...
        Q3*dtheta3;

        -0.5*H3*dtheta1, ...
        -0.5*P3*dtheta2 + 0.5*Q3*dtheta3, ...
        -0.5*Q3*dtheta2
    ];

end