function M = inertiaMatrix(q, p)

    % q is in radians inside this function
    theta2 = q(2);
    theta3 = q(3);

    H = ...
        p.Iyy1 ...
        + p.Ixx2*sin(theta2)^2 ...
        + p.Iyy2*cos(theta2)^2 ...
        + p.m2*p.lc2^2*cos(theta2)^2 ...
        + p.Ixx3*sin(theta2 + theta3)^2 ...
        + p.Iyy3*cos(theta2 + theta3)^2 ...
        + p.m3*(p.l2*cos(theta2) + p.lc3*cos(theta2 + theta3))^2;

    P = ...
        p.Izz2 ...
        + p.Izz3 ...
        + p.m2*p.lc2^2 ...
        + p.m3*( ...
            p.l2^2 ...
            + p.lc3^2 ...
            + 2*p.l2*p.lc3*cos(theta3) ...
        );

    Q = ...
        p.Izz3 ...
        + p.m3*( ...
            p.lc3^2 ...
            + p.l2*p.lc3*cos(theta3) ...
        );

    R = ...
        p.Izz3 ...
        + p.m3*p.lc3^2;

    M = [
        H, 0, 0;
        0, P, Q;
        0, Q, R
    ];

end